# -*- coding: utf-8 -*-
"""
seeds.py — Curated AI-native layer for CEO Intelligence OS.

These entities are NOT present as tables in the vault markdown, so they are
authored here, grounded in:
  - the CEO Intelligence prompt's agent catalog (per area / per company),
  - the vault's 05_Mapeo de Procesos folders,
  - the normalized collaborators + projects.

Everything here is marked confianza="Inferido" (propuesta) so the dashboard can
distinguish authored recommendations from verified vault data. The ETL merges
this with the parsed vault data; nothing here invents operational facts.
"""

# --------------------------------------------------------------------------- #
# AGENTS — propuesta de fuerza laboral de agentes por empresa / area / CEO.
# --------------------------------------------------------------------------- #
AGENTS = [
    # ---- CEO ----
    dict(empresa="AP", area="CEO", nombre="CEO Briefing Agent",
         proposito="Generar briefing diario/semanal con deltas, riesgos P0 y decisiones.",
         owner_humano="Alejandro", impacto=5, dificultad=2, prioridad="P0",
         prompt_base="Lee el vault CEO Intelligence, compara contra baseline, entrega briefing ejecutivo de 30s + 7/30/90."),
    dict(empresa="AP", area="CEO", nombre="Weekly Priorities Agent",
         proposito="Recalcular Top 10 prioridades por CEO Attention Score cada lunes.",
         owner_humano="Alejandro", impacto=4, dificultad=2, prioridad="P0",
         prompt_base="Ordena tareas y proyectos por impacto_caja, urgencia y riesgo; entrega 10 prioridades con owner y fecha."),
    dict(empresa="AP", area="CEO", nombre="Decision Register Agent",
         proposito="Capturar y dar seguimiento a decisiones CEO con fecha límite y riesgo de no decidir.",
         owner_humano="Alejandro", impacto=4, dificultad=2, prioridad="P1",
         prompt_base="Extrae decisiones pendientes del vault, marca fecha límite e información faltante."),
    dict(empresa="AP", area="CEO", nombre="Risk Radar Agent",
         proposito="Monitorear riesgos P0/P1, detectar nuevos y escalar bloqueos transversales.",
         owner_humano="Alejandro", impacto=5, dificultad=2, prioridad="P0",
         prompt_base="Recorre riesgos y bloqueos, recomputa Risk Score y alerta los P0 sin owner o sin fecha."),
    dict(empresa="AP", area="CEO", nombre="Cash Agent",
         proposito="Seguimiento de caja por cobrar (facturas/EDP) con compromiso fechado.",
         owner_humano="Julie", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Consolida facturas/EDP por cobrar, monto, responsable, fecha compromiso y evidencia."),
    dict(empresa="AP", area="CEO", nombre="Delta Analysis Agent",
         proposito="Comparar cada corte contra el baseline anterior y reportar cambios reales.",
         owner_humano="Alejandro", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Diff baseline vs estado actual; reporta entidades nuevas, modificadas y cerradas."),
    dict(empresa="AP", area="CEO", nombre="Vault Intelligence Agent",
         proposito="Normalizar archivos nuevos del vault y detectar duplicados/contradicciones.",
         owner_humano="Alejandro", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Escanea archivos nuevos/modificados, normaliza entidades y marca contradicciones."),
    dict(empresa="AP", area="CEO", nombre="Meeting Intelligence Agent",
         proposito="Convertir reuniones (Read AI/Calendar) en compromisos con owner y fecha.",
         owner_humano="Alejandro", impacto=3, dificultad=3, prioridad="P2",
         prompt_base="Toma minutas/transcripciones y extrae acuerdos accionables al backlog."),

    # ---- GEN+ ----
    dict(empresa="GEN+", area="Delivery BIM", nombre="Delivery BIM Agent",
         proposito="Estado por proyecto BIM: avance, entregable, validación y evidencia.",
         owner_humano="Fabrizio", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Consolida reportes BIM por proyecto y separa avance real de pendiente de validación."),
    dict(empresa="GEN+", area="Delivery BIM", nombre="Control de Alcance BIM Agent",
         proposito="Clasificar observaciones en alcance base / adicional / reproceso / fuera de alcance.",
         owner_humano="Israel", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Para Cañete/Faucett/Dovelas clasifica cada cambio y marca lo valorizable como adicional."),
    dict(empresa="GEN+", area="Caja / Cobranzas", nombre="Cobranzas Agent",
         proposito="Tablero diario de cobranza con compromiso de pago y recordatorios.",
         owner_humano="Julie", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Genera tablero caja: factura/EDP, monto, cliente, responsable, fecha, evidencia, estado."),
    dict(empresa="GEN+", area="Comercial B2B", nombre="Comercial B2B Agent",
         proposito="Pipeline B2B (UNCP/OSP/Nestlé/GORE) con siguiente paso y owner.",
         owner_humano="Daniella", impacto=3, dificultad=3, prioridad="P2",
         prompt_base="Mantén pipeline B2B con etapa, TDR, próximo paso, fecha y probabilidad."),
    dict(empresa="GEN+", area="Producto digital", nombre="Propuestas / Contratos Agent",
         proposito="Generar propuestas y contratos a partir de discovery (ESPARQ, VisionPro).",
         owner_humano="Fabrizio", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Desde discovery genera propuesta, alcance, DoD, precio y contrato base."),
    dict(empresa="GEN+", area="Delivery BIM", nombre="QA/QC BIM Agent",
         proposito="Checklist de calidad por entregable BIM antes de envío al cliente.",
         owner_humano="Kevin", impacto=3, dificultad=3, prioridad="P2",
         prompt_base="Aplica checklist QA/QC por disciplina y bloquea entregas sin evidencia."),

    # ---- AECODE ----
    dict(empresa="AECODE", area="Training / coordinación académica", nombre="Training Operations Agent",
         proposito="Tablero por diplomado: rúbrica, entregable, certificado, sustitutorio, bloqueo.",
         owner_humano="Carolina", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Consolida estado académico por diplomado y marca cierres y reclamos potenciales."),
    dict(empresa="AECODE", area="Training / coordinación académica", nombre="Certificados Agent",
         proposito="Emisión y trazabilidad de certificados (CIP, sustitutorios) con evidencia.",
         owner_humano="Patrick", impacto=4, dificultad=2, prioridad="P1",
         prompt_base="Genera y registra certificados con verificación de notas y entregables."),
    dict(empresa="AECODE", area="Comercial B2C", nombre="Ventas B2C Agent",
         proposito="SLA por lead, seguimiento y corte oficial de ventas (completa vs cuota).",
         owner_humano="Talia", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Aplica SLA por lead, separa venta completa/cuota/registro y entrega cifra oficial."),
    dict(empresa="AECODE", area="Marketing / growth", nombre="Marketing Attribution Agent",
         proposito="Dashboard pieza→canal→lead→venta para saber qué convierte.",
         owner_humano="Jessica", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Integra GHL y campañas, atribuye leads y ventas por pieza y canal."),
    dict(empresa="AECODE", area="Summit / eventos", nombre="Sponsors Agent",
         proposito="Cruce sponsor→pago→beneficio→delegación→stand→ponente con corte diario.",
         owner_humano="Paola", impacto=5, dificultad=3, prioridad="P0",
         prompt_base="Mantén CRM sponsor vivo y cruza pago, beneficio y delegación; alerta sponsors fríos."),
    dict(empresa="AECODE", area="Summit / eventos", nombre="Summit Agent",
         proposito="Coordinar web/app/agenda/proveedores del AI Construction Summit.",
         owner_humano="Marlon", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Sigue QA web, test app, agenda y proveedores con estado y owner."),
    dict(empresa="AECODE", area="Producto digital", nombre="Producto Digital / Testing Agent",
         proposito="Separar handoff de diseño de implementación dev y QA.",
         owner_humano="Yary", impacto=3, dificultad=3, prioridad="P2",
         prompt_base="Para Fase 2/3 separa diseño listo, dev pendiente y QA pendiente con owner."),
    dict(empresa="AECODE", area="Startup / convocatorias", nombre="Startup / Convocatorias Agent",
         proposito="Checklist de convocatorias (deck, métricas, evidencia, ensayo, owner).",
         owner_humano="Daniella", impacto=3, dificultad=2, prioridad="P2",
         prompt_base="Aplica checklist startup y agenda hitos de convocatorias (StartUPC, etc.)."),

    # ---- VisionPro ----
    dict(empresa="VisionPro", area="VisionPro / computer vision", nombre="Demo / Deployment Agent",
         proposito="Demo web estable + diagnóstico de conectividad obra + fallback edge/offline.",
         owner_humano="Emanuel", impacto=5, dificultad=4, prioridad="P0",
         prompt_base="Sigue estado de demo, conectividad y despliegue; prioriza funcionalidades IA P0."),
    dict(empresa="VisionPro", area="VisionPro / computer vision", nombre="Computer Vision Product Agent",
         proposito="Roadmap IA PDK Ascent priorizado por caso de uso vendible.",
         owner_humano="Marlon", impacto=4, dificultad=4, prioridad="P1",
         prompt_base="Prioriza backlog PDK por valor comercial y corta un MVP vendible."),

    # ---- THESIA ----
    dict(empresa="THESIA", area="Startup / convocatorias", nombre="Research / Tesis Agent",
         proposito="Estructura de tesis/papers y traspaso de información con fechas.",
         owner_humano="Fabrizio", impacto=2, dificultad=2, prioridad="P3",
         prompt_base="Organiza tesis Juan, presupuesto y traspaso; define solicitud y fecha límite."),

    # ---- AgentFlow ----
    dict(empresa="AgentFlow", area="AgentFlow / automatización", nombre="Workflow Migration Agent",
         proposito="Migrar primer flujo con entrada, salida, log y fallback.",
         owner_humano="Emanuel", impacto=4, dificultad=3, prioridad="P1",
         prompt_base="Toma un proceso manual y produce flujo migrado con log y evidencia."),
    dict(empresa="AgentFlow", area="AgentFlow / automatización", nombre="Context Pipeline Agent",
         proposito="WhatsApp/Drive/Gmail → vault normalizado → dashboard.",
         owner_humano="Emanuel", impacto=5, dificultad=4, prioridad="P1",
         prompt_base="Construye pipeline de ingesta que normaliza fuentes y alimenta el vault."),
]

# --------------------------------------------------------------------------- #
# PROCESOS — desde 05_Mapeo de Procesos + procesos núcleo de operación.
# --------------------------------------------------------------------------- #
PROCESOS = [
    dict(empresa="GEN+", area="Caja / Cobranzas", nombre="Cobranza GEN+",
         input="Facturas/EDP emitidas", output="Pago cobrado + evidencia",
         owner="Julie", sla="Diario", herramientas=["Excel", "WhatsApp"],
         herramientas_ia=["Cobranzas Agent"], agente="Cobranzas Agent",
         estado="manual", automatizable=True, prioridad_auto="P0",
         claridad_input=0.9, claridad_output=0.7, owner_claro=1.0, sla_claro=0.5,
         trazabilidad=0.4, automatizacion=0.2, metrica=0.5),
    dict(empresa="GEN+", area="Delivery BIM", nombre="Control de Alcance BIM",
         input="Observaciones de supervisión", output="Matriz base/adicional/reproceso",
         owner="Israel", sla="Por proyecto", herramientas=["Revit", "Excel"],
         herramientas_ia=["Control de Alcance BIM Agent"], agente="Control de Alcance BIM Agent",
         estado="manual", automatizable=True, prioridad_auto="P0",
         claridad_input=0.6, claridad_output=0.5, owner_claro=0.8, sla_claro=0.4,
         trazabilidad=0.4, automatizacion=0.1, metrica=0.4),
    dict(empresa="GEN+", area="Comercial B2B", nombre="Ventas B2B",
         input="Lead / TDR", output="Propuesta + contrato",
         owner="Daniella", sla="Por oportunidad", herramientas=["Drive", "Canva"],
         herramientas_ia=["Comercial B2B Agent", "Propuestas / Contratos Agent"],
         agente="Comercial B2B Agent", estado="funcional", automatizable=True, prioridad_auto="P2",
         claridad_input=0.6, claridad_output=0.7, owner_claro=0.7, sla_claro=0.4,
         trazabilidad=0.5, automatizacion=0.3, metrica=0.5),
    dict(empresa="AECODE", area="Summit / eventos", nombre="Gestión de Evento (Summit)",
         input="Sponsors + agenda + producción", output="Evento ejecutado + caja",
         owner="Erika", sla="Diario en sprint", herramientas=["Sheets", "GHL", "Canva"],
         herramientas_ia=["Sponsors Agent", "Summit Agent"], agente="Sponsors Agent",
         estado="funcional", automatizable=True, prioridad_auto="P0",
         claridad_input=0.7, claridad_output=0.7, owner_claro=0.8, sla_claro=0.6,
         trazabilidad=0.5, automatizacion=0.3, metrica=0.6),
    dict(empresa="AECODE", area="Training / coordinación académica", nombre="Coordinación Académica + Postventa",
         input="Programa + alumnos", output="Certificados + cierre académico",
         owner="Carolina", sla="Por diplomado", herramientas=["Zoom", "Sheets"],
         herramientas_ia=["Training Operations Agent", "Certificados Agent"],
         agente="Training Operations Agent", estado="manual", automatizable=True, prioridad_auto="P0",
         claridad_input=0.7, claridad_output=0.6, owner_claro=0.8, sla_claro=0.5,
         trazabilidad=0.5, automatizacion=0.2, metrica=0.5),
    dict(empresa="AECODE", area="Comercial B2C", nombre="Ventas B2C Training",
         input="Lead marketing", output="Venta + matrícula",
         owner="Talia", sla="SLA por lead", herramientas=["GHL", "WhatsApp"],
         herramientas_ia=["Ventas B2C Agent"], agente="Ventas B2C Agent",
         estado="funcional", automatizable=True, prioridad_auto="P0",
         claridad_input=0.7, claridad_output=0.6, owner_claro=0.8, sla_claro=0.4,
         trazabilidad=0.4, automatizacion=0.3, metrica=0.5),
    dict(empresa="AECODE", area="Marketing / growth", nombre="Lanzamiento / Pre Congreso",
         input="Calendario campaña", output="Leads trazables",
         owner="Arantxa", sla="Sprint 24-72h", herramientas=["Meta Ads", "GHL", "Canva"],
         herramientas_ia=["Marketing Attribution Agent"], agente="Marketing Attribution Agent",
         estado="funcional", automatizable=True, prioridad_auto="P1",
         claridad_input=0.6, claridad_output=0.5, owner_claro=0.8, sla_claro=0.6,
         trazabilidad=0.3, automatizacion=0.3, metrica=0.4),
    dict(empresa="AECODE", area="Producto digital", nombre="Creación de Curso / Producto",
         input="Outline + handoff", output="Producto digital operativo",
         owner="Yary", sla="Por fase", herramientas=["Figma", "HTML", "Claude Code"],
         herramientas_ia=["Producto Digital / Testing Agent"], agente="Producto Digital / Testing Agent",
         estado="funcional", automatizable=True, prioridad_auto="P2",
         claridad_input=0.7, claridad_output=0.6, owner_claro=0.8, sla_claro=0.4,
         trazabilidad=0.5, automatizacion=0.4, metrica=0.4),
    dict(empresa="VisionPro", area="VisionPro / computer vision", nombre="Implementación en Obra",
         input="Cámaras + conectividad", output="Demo / monitoreo operativo",
         owner="Emanuel", sla="Por despliegue", herramientas=["AWS", "Jetson", "Python"],
         herramientas_ia=["Demo / Deployment Agent"], agente="Demo / Deployment Agent",
         estado="manual", automatizable=True, prioridad_auto="P0",
         claridad_input=0.5, claridad_output=0.4, owner_claro=0.7, sla_claro=0.3,
         trazabilidad=0.4, automatizacion=0.2, metrica=0.3),
    dict(empresa="AECODE", area="Startup / convocatorias", nombre="Postulación a Startup",
         input="Convocatoria", output="Aplicación + pitch",
         owner="Daniella", sla="Por convocatoria", herramientas=["Drive", "Canva"],
         herramientas_ia=["Startup / Convocatorias Agent"], agente="Startup / Convocatorias Agent",
         estado="caotico", automatizable=True, prioridad_auto="P2",
         claridad_input=0.5, claridad_output=0.5, owner_claro=0.7, sla_claro=0.3,
         trazabilidad=0.3, automatizacion=0.2, metrica=0.3),
    dict(empresa="AgentFlow", area="AgentFlow / automatización", nombre="Migración de Workflows",
         input="Proceso manual", output="Flujo automatizado + log",
         owner="Emanuel", sla="Por flujo", herramientas=["n8n", "Claude Code"],
         herramientas_ia=["Workflow Migration Agent", "Context Pipeline Agent"],
         agente="Workflow Migration Agent", estado="manual", automatizable=True, prioridad_auto="P1",
         claridad_input=0.6, claridad_output=0.5, owner_claro=0.8, sla_claro=0.4,
         trazabilidad=0.4, automatizacion=0.2, metrica=0.3),
    dict(empresa="AP", area="Knowledge OS", nombre="Knowledge OS / Context Pipeline",
         input="WhatsApp/Drive/Gmail/notas", output="Vault normalizado + dashboard",
         owner="Alejandro", sla="Cada 3h / on-demand", herramientas=["Codex", "Claude Code", "Obsidian"],
         herramientas_ia=["Vault Intelligence Agent", "Context Pipeline Agent"],
         agente="Vault Intelligence Agent", estado="funcional", automatizable=True, prioridad_auto="P1",
         claridad_input=0.6, claridad_output=0.8, owner_claro=1.0, sla_claro=0.7,
         trazabilidad=0.7, automatizacion=0.5, metrica=0.5),
]

# --------------------------------------------------------------------------- #
# HERRAMIENTAS IA — catálogo recomendado.
# --------------------------------------------------------------------------- #
TOOLS = [
    dict(nombre="Claude Code", categoria="Agente/Dev", casos=["Apps", "ETL", "Automatización", "Dashboards"], nivel="Core"),
    dict(nombre="Codex", categoria="Agente/Contexto", casos=["Normalización vault", "Reportes", "Contexto"], nivel="Core"),
    dict(nombre="Grok", categoria="Investigación", casos=["Tendencias", "Análisis crítico"], nivel="Apoyo"),
    dict(nombre="GHL (GoHighLevel)", categoria="CRM/Marketing", casos=["Leads", "Atribución", "Automatización comercial"], nivel="Operativo"),
    dict(nombre="n8n", categoria="Automatización", casos=["Workflows", "Integraciones"], nivel="Operativo"),
    dict(nombre="Read AI", categoria="Reuniones", casos=["Minutas", "Compromisos"], nivel="Apoyo"),
    dict(nombre="Canva / IA", categoria="Diseño", casos=["Materiales comerciales", "Piezas"], nivel="Operativo"),
    dict(nombre="Obsidian", categoria="Segundo cerebro", casos=["Vault", "Trazabilidad", "Contexto"], nivel="Core"),
    dict(nombre="Google Drive/Sheets", categoria="Datos/Docs", casos=["Tableros vivos", "Fuentes"], nivel="Operativo"),
]

# --------------------------------------------------------------------------- #
# AI PROFILE por colaborador — herramientas, agentes y delegables.
# claves por nombre canónico de colaborador. Valores 0..1 para los scores.
# --------------------------------------------------------------------------- #
AI_PROFILE = {
    "Alejandro": dict(uso_ia=0.9, contexto=0.9, traza=0.8, autom=0.6, doc=0.8, delega=0.8, mejora=0.9,
                      tools=["Claude Code", "Codex", "Grok", "Obsidian"],
                      tools_rec=["CEO Briefing Agent", "Delta Analysis Agent"],
                      agentes=["CEO Briefing Agent", "Risk Radar Agent", "Weekly Priorities Agent"],
                      delegables=["Briefing diario", "Priorización", "Detección de riesgos"]),
    "Julie": dict(uso_ia=0.5, contexto=0.7, traza=0.5, autom=0.3, doc=0.6, delega=0.5, mejora=0.6,
                  tools=["Excel", "WhatsApp"], tools_rec=["Cobranzas Agent", "Sheets IA"],
                  agentes=["Cobranzas Agent", "Sponsors Agent"],
                  delegables=["Tablero de caja diario", "Recordatorios de cobro"]),
    "Marlon": dict(uso_ia=0.7, contexto=0.6, traza=0.5, autom=0.6, doc=0.5, delega=0.5, mejora=0.7,
                   tools=["Claude Code", "C#", "Canva"], tools_rec=["Summit Agent", "QA Agent"],
                   agentes=["Summit Agent", "Computer Vision Product Agent"],
                   delegables=["QA web", "Seguimiento de certificados"]),
    "Fabrizio": dict(uso_ia=0.8, contexto=0.7, traza=0.6, autom=0.6, doc=0.7, delega=0.5, mejora=0.7,
                     tools=["Claude Code", "Revit", "Codex"], tools_rec=["Delivery BIM Agent", "Propuestas Agent"],
                     agentes=["Delivery BIM Agent", "Propuestas / Contratos Agent"],
                     delegables=["Reportes de cierre", "Documentación de entregables"]),
    "Yary": dict(uso_ia=0.7, contexto=0.6, traza=0.6, autom=0.4, doc=0.6, delega=0.5, mejora=0.6,
                 tools=["Figma", "HTML"], tools_rec=["Producto Digital / Testing Agent"],
                 agentes=["Producto Digital / Testing Agent"],
                 delegables=["Handoff dev/QA", "Documentación de componentes"]),
    "Carolina": dict(uso_ia=0.4, contexto=0.6, traza=0.6, autom=0.3, doc=0.6, delega=0.5, mejora=0.5,
                     tools=["Sheets", "Zoom"], tools_rec=["Training Operations Agent"],
                     agentes=["Training Operations Agent", "Certificados Agent"],
                     delegables=["Tablero por diplomado", "Estado de certificados"]),
    "Talia": dict(uso_ia=0.5, contexto=0.6, traza=0.5, autom=0.4, doc=0.5, delega=0.5, mejora=0.6,
                  tools=["GHL", "WhatsApp"], tools_rec=["Ventas B2C Agent"],
                  agentes=["Ventas B2C Agent"], delegables=["SLA por lead", "Reporte de funnel"]),
    "Genesis": dict(uso_ia=0.5, contexto=0.5, traza=0.4, autom=0.4, doc=0.4, delega=0.4, mejora=0.5,
                    tools=["GHL", "WhatsApp"], tools_rec=["Ventas B2C Agent"],
                    agentes=["Ventas B2C Agent"], delegables=["Seguimiento de leads", "Corte de ventas"]),
    "Yadira": dict(uso_ia=0.4, contexto=0.5, traza=0.4, autom=0.3, doc=0.4, delega=0.4, mejora=0.5,
                   tools=["GHL"], tools_rec=["Ventas B2C Agent"],
                   agentes=["Ventas B2C Agent"], delegables=["Separar venta completa/cuota"]),
    "Erika": dict(uso_ia=0.5, contexto=0.7, traza=0.5, autom=0.4, doc=0.6, delega=0.5, mejora=0.6,
                  tools=["Sheets", "WhatsApp"], tools_rec=["Sponsors Agent"],
                  agentes=["Sponsors Agent"], delegables=["CRM sponsors vivo", "Corte sponsor diario"]),
    "Paola": dict(uso_ia=0.5, contexto=0.7, traza=0.6, autom=0.4, doc=0.6, delega=0.5, mejora=0.6,
                  tools=["Sheets"], tools_rec=["Sponsors Agent"],
                  agentes=["Sponsors Agent"], delegables=["Cruce pago-beneficio-delegación"]),
    "Arantxa": dict(uso_ia=0.6, contexto=0.6, traza=0.4, autom=0.5, doc=0.5, delega=0.5, mejora=0.6,
                    tools=["Meta Ads", "GHL", "Canva"], tools_rec=["Marketing Attribution Agent"],
                    agentes=["Marketing Attribution Agent"], delegables=["Sprint de campaña", "Landing"]),
    "Jessica": dict(uso_ia=0.6, contexto=0.5, traza=0.4, autom=0.6, doc=0.5, delega=0.5, mejora=0.6,
                    tools=["GHL"], tools_rec=["Marketing Attribution Agent"],
                    agentes=["Marketing Attribution Agent"], delegables=["Flujos GHL", "Tracking end-to-end"]),
    "Enma": dict(uso_ia=0.6, contexto=0.5, traza=0.4, autom=0.4, doc=0.5, delega=0.4, mejora=0.6,
                 tools=["Canva", "TikTok"], tools_rec=["Marketing Attribution Agent"],
                 agentes=["Marketing Attribution Agent"], delegables=["Piezas", "Brochures versión única"]),
    "Anggie": dict(uso_ia=0.6, contexto=0.5, traza=0.4, autom=0.5, doc=0.4, delega=0.4, mejora=0.6,
                   tools=["Agentes marketing"], tools_rec=["Marketing Attribution Agent"],
                   agentes=["Marketing Attribution Agent"], delegables=["Dashboard de métricas"]),
    "Kevin": dict(uso_ia=0.6, contexto=0.6, traza=0.5, autom=0.6, doc=0.5, delega=0.5, mejora=0.6,
                  tools=["Revit", "Python", "C#"], tools_rec=["QA/QC BIM Agent"],
                  agentes=["QA/QC BIM Agent", "Delivery BIM Agent"], delegables=["Scripts BESCO", "Plataforma"]),
    "Israel": dict(uso_ia=0.4, contexto=0.6, traza=0.5, autom=0.3, doc=0.5, delega=0.4, mejora=0.5,
                   tools=["Revit", "InfraWorks"], tools_rec=["Control de Alcance BIM Agent"],
                   agentes=["Control de Alcance BIM Agent"], delegables=["Matriz de alcance"]),
    "Robert Herrera": dict(uso_ia=0.3, contexto=0.5, traza=0.4, autom=0.2, doc=0.4, delega=0.3, mejora=0.4,
                           tools=["Revit"], tools_rec=["Delivery BIM Agent"],
                           agentes=["Delivery BIM Agent"], delegables=["Reporte de avance estandarizado"]),
    "Luis Vergara": dict(uso_ia=0.3, contexto=0.5, traza=0.4, autom=0.2, doc=0.4, delega=0.3, mejora=0.4,
                         tools=["Revit", "Rhino"], tools_rec=["Delivery BIM Agent"],
                         agentes=["Delivery BIM Agent"], delegables=["Documentar flujos y cambios"]),
    "Guisella": dict(uso_ia=0.3, contexto=0.5, traza=0.4, autom=0.2, doc=0.4, delega=0.3, mejora=0.4,
                     tools=["Revit"], tools_rec=["Control de Alcance BIM Agent"],
                     agentes=["Control de Alcance BIM Agent"], delegables=["Matriz dovela", "Valorización de cambios"]),
    "Daniella": dict(uso_ia=0.7, contexto=0.7, traza=0.5, autom=0.4, doc=0.6, delega=0.5, mejora=0.7,
                     tools=["Canva", "Claude"], tools_rec=["Comercial B2B Agent", "Startup Agent"],
                     agentes=["Startup / Convocatorias Agent", "Comercial B2B Agent"],
                     delegables=["Materiales comerciales", "Postmortems"]),
    "Emanuel": dict(uso_ia=0.7, contexto=0.5, traza=0.5, autom=0.7, doc=0.5, delega=0.6, mejora=0.7,
                    tools=["Python", "AWS", "n8n"], tools_rec=["Workflow Migration Agent"],
                    agentes=["Workflow Migration Agent", "Demo / Deployment Agent", "Context Pipeline Agent"],
                    delegables=["Migración de flujos", "Diagnóstico conectividad"]),
    "Anderson": dict(uso_ia=0.4, contexto=0.3, traza=0.3, autom=0.4, doc=0.3, delega=0.3, mejora=0.4,
                     tools=["Dev"], tools_rec=["Summit Agent"], agentes=["Summit Agent"],
                     delegables=["Testeo App Summit"]),
    "Yudely": dict(uso_ia=0.4, contexto=0.4, traza=0.4, autom=0.3, doc=0.4, delega=0.3, mejora=0.4,
                   tools=["Sheets"], tools_rec=["Producto Digital / Testing Agent"],
                   agentes=["Producto Digital / Testing Agent"], delegables=["Revisión Fase 3"]),
    "Patrick": dict(uso_ia=0.4, contexto=0.5, traza=0.5, autom=0.3, doc=0.5, delega=0.4, mejora=0.5,
                    tools=["Zoom", "Sheets"], tools_rec=["Certificados Agent"],
                    agentes=["Certificados Agent"], delegables=["Matriz certificados/notas/recursos"]),
}
